# Generated by Django 5.2.17 on 2026-08-19 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('image_url', models.URLField(blank=True, help_text='Fallback external image URL', max_length=500)),
                ('is_featured', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ContactEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('subject', models.CharField(blank=True, default='Jewellery Inquiry / Private Consultation', max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Contact Enquiry',
                'verbose_name_plural': 'Contact Enquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HeroBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='The Art of Forever', max_length=200)),
                ('subtitle', models.TextField(default='Jewellery designed to become part of your story.')),
                ('tagline', models.CharField(blank=True, default='HAUTE JOAILLERIE & TIMELESS BRILLIANCE', max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to='hero/')),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('button_text', models.CharField(default='DISCOVER THE COLLECTION', max_length=60)),
                ('button_link', models.CharField(default='#collections', max_length=120)),
                ('secondary_button_text', models.CharField(blank=True, default='EXPLORE OUR STORY →', max_length=60)),
                ('secondary_button_link', models.CharField(blank=True, default='#story', max_length=120)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Hero Banner',
                'verbose_name_plural': 'Hero Banners',
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Newsletter Subscriber',
                'verbose_name_plural': 'Newsletter Subscribers',
                'ordering': ['-subscribed_at'],
            },
        ),
        migrations.CreateModel(
            name='ShopSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(default='AURELIA FINE JEWELLERY', max_length=120)),
                ('tagline', models.CharField(default='The Art of Forever — Mastercrafted Haute Joaillerie', max_length=200)),
                ('phone_number', models.CharField(default='+91 98765 43210', max_length=40)),
                ('whatsapp_number', models.CharField(default='+91 98765 43210', max_length=40)),
                ('whatsapp_message', models.TextField(default='Hello AURELIA, I would like to know more about your jewellery collection.')),
                ('email', models.EmailField(default='hello@aureliajewels.com', max_length=254)),
                ('address', models.CharField(default='123 Luxury Street, Chennai, Tamil Nadu, India', max_length=255)),
                ('opening_hours', models.CharField(default='Mon – Sat: 10:30 AM – 8:30 PM | Sun: 11:00 AM – 7:00 PM', max_length=255)),
                ('google_map_embed_url', models.TextField(default='https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3886.589139886364!2d80.2452!3d13.0475!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3a5266497f1f9e53%3A0x6b4f7b21e8d6411!2sKhader%20Nawaz%20Khan%20Rd%2C%20Nungambakkam%2C%20Chennai%2C%20Tamil%20Nadu!5e0!3m2!1sen!2sin!4v1700000000000')),
                ('google_map_direct_url', models.URLField(default='https://maps.google.com/?q=Khader+Nawaz+Khan+Road+Nungambakkam+Chennai', max_length=500)),
                ('facebook_url', models.URLField(blank=True, default='https://facebook.com/aureliajewels')),
                ('instagram_url', models.URLField(blank=True, default='https://instagram.com/aureliajewels')),
                ('pinterest_url', models.URLField(blank=True, default='https://pinterest.com/aureliajewels')),
            ],
            options={
                'verbose_name': 'Shop Settings',
                'verbose_name_plural': 'Shop Settings',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=120)),
                ('customer_title', models.CharField(blank=True, default='Private Collector, Chennai', max_length=150)),
                ('quote', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('customer_image', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('customer_image_url', models.URLField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['-rating', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JewelleryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('material', models.CharField(default='18K Yellow Gold & Solitaire Diamond', max_length=150)),
                ('carat_weight', models.CharField(blank=True, default='1.50 CT', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('image_url', models.URLField(blank=True, help_text='Primary product image URL', max_length=500)),
                ('hover_image', models.ImageField(blank=True, null=True, upload_to='products/hover/')),
                ('hover_image_url', models.URLField(blank=True, help_text='Secondary/model hover image URL', max_length=500)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_bestseller', models.BooleanField(default=False)),
                ('is_new', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='jewellery.category')),
            ],
            options={
                'verbose_name': 'Jewellery Product',
                'verbose_name_plural': 'Jewellery Products',
                'ordering': ['-is_bestseller', '-created_at'],
            },
        ),
    ]
