# Generated by Django 5.2.17 on 2026-08-25 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jewellery", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shopsettings",
            name="email",
            field=models.EmailField(default="hello@vetrijewels.com", max_length=254),
        ),
        migrations.AlterField(
            model_name="shopsettings",
            name="facebook_url",
            field=models.URLField(
                blank=True, default="https://facebook.com/vetrijewels"
            ),
        ),
        migrations.AlterField(
            model_name="shopsettings",
            name="instagram_url",
            field=models.URLField(
                blank=True, default="https://instagram.com/vetrijewels"
            ),
        ),
        migrations.AlterField(
            model_name="shopsettings",
            name="pinterest_url",
            field=models.URLField(
                blank=True, default="https://pinterest.com/vetrijewels"
            ),
        ),
        migrations.AlterField(
            model_name="shopsettings",
            name="shop_name",
            field=models.CharField(default="VETRI FINE JEWELLERY", max_length=120),
        ),
        migrations.AlterField(
            model_name="shopsettings",
            name="whatsapp_message",
            field=models.TextField(
                default="Hello VETRI, I would like to know more about your jewellery collection."
            ),
        ),
    ]
