# Generated by Django 5.2.17 on 2026-08-25 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                blank=True, help_text="e.g. card, upi, netbanking", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="tax_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="order",
            name="transaction_id",
            field=models.CharField(
                blank=True,
                help_text="Cashfree payment ID (cf_payment_id)",
                max_length=100,
            ),
        ),
    ]
